/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface Pcr0ManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addPCR0"
      | "isPCR0Set"
      | "owner"
      | "pcr0Mapping"
      | "removePCR0"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OwnershipTransferred" | "PCR0Added" | "PCR0Removed"
  ): EventFragment;

  encodeFunctionData(functionFragment: "addPCR0", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "isPCR0Set",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pcr0Mapping",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removePCR0",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addPCR0", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPCR0Set", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pcr0Mapping",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "removePCR0", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PCR0AddedEvent {
  export type InputTuple = [key: BytesLike];
  export type OutputTuple = [key: string];
  export interface OutputObject {
    key: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PCR0RemovedEvent {
  export type InputTuple = [key: BytesLike];
  export type OutputTuple = [key: string];
  export interface OutputObject {
    key: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Pcr0Manager extends BaseContract {
  connect(runner?: ContractRunner | null): Pcr0Manager;
  waitForDeployment(): Promise<this>;

  interface: Pcr0ManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addPCR0: TypedContractMethod<[pcr0: BytesLike], [void], "nonpayable">;

  isPCR0Set: TypedContractMethod<[pcr0: BytesLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pcr0Mapping: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  removePCR0: TypedContractMethod<[pcr0: BytesLike], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addPCR0"
  ): TypedContractMethod<[pcr0: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isPCR0Set"
  ): TypedContractMethod<[pcr0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pcr0Mapping"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "removePCR0"
  ): TypedContractMethod<[pcr0: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PCR0Added"
  ): TypedContractEvent<
    PCR0AddedEvent.InputTuple,
    PCR0AddedEvent.OutputTuple,
    PCR0AddedEvent.OutputObject
  >;
  getEvent(
    key: "PCR0Removed"
  ): TypedContractEvent<
    PCR0RemovedEvent.InputTuple,
    PCR0RemovedEvent.OutputTuple,
    PCR0RemovedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PCR0Added(bytes32)": TypedContractEvent<
      PCR0AddedEvent.InputTuple,
      PCR0AddedEvent.OutputTuple,
      PCR0AddedEvent.OutputObject
    >;
    PCR0Added: TypedContractEvent<
      PCR0AddedEvent.InputTuple,
      PCR0AddedEvent.OutputTuple,
      PCR0AddedEvent.OutputObject
    >;

    "PCR0Removed(bytes32)": TypedContractEvent<
      PCR0RemovedEvent.InputTuple,
      PCR0RemovedEvent.OutputTuple,
      PCR0RemovedEvent.OutputObject
    >;
    PCR0Removed: TypedContractEvent<
      PCR0RemovedEvent.InputTuple,
      PCR0RemovedEvent.OutputTuple,
      PCR0RemovedEvent.OutputObject
    >;
  };
}
